# Generated by Django 4.2.1 on 2023-06-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
